name: Keep Render Alive

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -f https://interviewprephub.onrender.com/api/company/ping || echo "Ping failed"

